[package]
name = "relational-engine-owner-tests"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
relational-engine-scratchpad = { path = "../../../personal/relational-engine/rust" }

[[test]]
name = "memory_owner"
path = "nio/mem_test.rs"

[[test]]
name = "string_owner"
path = "text/string_test.rs"

[[test]]
name = "ffi_memory_owner"
path = "ffi/memory_test.rs"
