// tests/darling/panel/panel_events_test.c — mirrors darling panel event adders
//
// The per-class macros (DECLARE_EVENTS/IMPLEMENT_EVENTS) generate
// Panel_add<Kind>Event and ScrollPanel_add<Kind>Event from the class name. This
// proves a class-level registration lands on the class's Element, that dispatch
// bubbles deepest-first, and that a ScrollPanel wired to its own scroll handler
// actually scrolls.

#include <stdio.h>

#include "c23/event_invoke.h"
#include "panel/panel.h"
#include "panel/scroll_panel.h"
#include "ui/element.h"

static int g_fail = 0;
#define CHECK(cond)                                                        \
    do {                                                                   \
        if (!(cond)) {                                                     \
            printf("FAIL %s:%d %s\n", __FILE__, __LINE__, #cond);          \
            g_fail++;                                                      \
        }                                                                  \
    } while (0)

static bool near(float a, float b) { return (a > b ? a - b : b - a) < 0.01f; }

typedef struct Trace { int ids[8]; int count; } Trace;
static void push(Trace *t, int id) { if (t->count < 8) t->ids[t->count++] = id; }

static void on_scroll_child(Element *e, const Scroll *s, void *ud)  { (void)e; (void)s; push(ud, 1); }
static void on_scroll_parent(Element *e, const Scroll *s, void *ud) { (void)e; (void)s; push(ud, 2); }

static void on_wheel(Element *e, const Scroll *s, void *ud) {
    (void)e;
    ScrollPanel_scrollBy(ud, s->dx, s->dy);
}

#include "darling/test_application.h"
int main(void) {
    // ── Panel_add<Kind>Event: per-class, generated by the macro ─────────────
    Panel *root = Panel(200, 150);
    Panel *child = Panel(100, 100);
    CHECK(root && child);
    CHECK(Panel_add(root, child) == child);

    Trace trace = {0};
    CHECK(Panel_addScrollEvent(child, (ScrollEvent){ .onScroll = on_scroll_child,  .userdata = &trace }) == child);
    CHECK(Panel_addScrollEvent(root,  (ScrollEvent){ .onScroll = on_scroll_parent, .userdata = &trace }) == root);

    Event sc = { .kind = EV_SCROLL, .x = 10, .y = 10, .dy = 5 };
    CHECK(Element_dispatchEvent(Panel_graphics(root), &sc));
    CHECK(trace.count == 2);
    CHECK(trace.ids[0] == 1);   // the child (deepest) first
    CHECK(trace.ids[1] == 2);   // then the parent

    Panel_destroy(root);        // owns the child wrapper + the Element tree

    // ── a ScrollPanel scrolling from its own handler ────────────────────────
    ScrollPanel *sp = ScrollPanel(200, 150);
    CHECK(sp && ScrollPanel_graphics(sp));

    ElementDesc dd = {0};
    dd.width = 200; dd.height = 1000;
    Element *doc = Element(&dd);
    ScrollPanel_setContent(sp, doc);

    // the macro-generated adder, pointed straight at ScrollPanel_scrollBy
    CHECK(ScrollPanel_addScrollEvent(sp, (ScrollEvent){ .onScroll = on_wheel, .userdata = sp }) == sp);

    Event wheel = { .kind = EV_SCROLL, .x = 20, .y = 20, .dx = 0, .dy = 120 };
    CHECK(Element_dispatchEvent(ScrollPanel_graphics(sp), &wheel));

    float ox, oy;
    ScrollPanel_getOffset(sp, &ox, &oy);
    CHECK(near(oy, 120.0f));    // the wheel really scrolled the viewport

    ScrollPanel_destroy(sp);
    if (g_fail == 0) printf("panel_events_test: ALL PASS\n");
    return g_fail == 0 ? 0 : 1;
}
